o/snapstate: fix error handling single snap refresh
I noticed that refreshing to a non-existent revision returned an
unrelated error message:
```
$ sudo snap refresh --revision=1337 hello
error: cannot refresh "hello": expected exactly one snap to install/update
"expected exactly one snap to install/update".
```

The issue was that we were expecting a single error from the store when
calling SingleOpError() and any other error caused it to return nil
instead (which seems odd/risky anyway). This was triggered by the store
also returning an "unauthenticated" error along with the usual "that
revision doesn't exist" error. I don't know why that error was included,
since I was logged in. I considered whether this was just a store bug
the store API docs (https://api.snapcraft.io/docs/) mention
"allow_unauthenticated snaps" so it seems to be expected/possible behaviour.
With the fix:
```
$ sudo snap refresh --revision=1337 hello
error: snap "hello" revision 1337 not available (see 'snap info hello')
```

Signed-off-by: Miguel Pires <miguel.pires@canonical.com>